### ISSUE TITLE
[Suggestion] Use the light property of power poles instead of creating lamps

### ISSUE THREAD

**Issue by Bilka2** [Yousei9/Lighted-Poles-Plus#3]
Electric poles can have a light set directly on the prototype (https://wiki.factorio.com/Prototype/ElectricPole#light), so you don't have to do any dummy entity shenanigans to get lighted power poles :D

**Comment by Yousei9** [comment]
Does minimum_darkness make light act according to day/night cycle or is that name misleading?
If light doesn't turn off during day it'd look silly, but I could live with it.

What I can't live with is lighted poles without energy consumption.
If I have to simulate consumption I might as well keep the lamps.

**Comment by Bilka2** [comment]
> Does minimum_darkness make light act according to day/night cycle?

Yes.

> What I can't live with is lighted poles without energy consumption.
If I have to simulate consumption I might as well keep the lamps.

I didn't realize that the lights should use power, it definitely throws a wrench into my idea.
