### ISSUE TITLE
Compatibility with reskins-bobs

### ISSUE THREAD

**Issue by oorzkws** [Yousei9/Lighted-Poles-Plus#4]
![image](https://user-images.githubusercontent.com/65210810/85235660-1da4ce00-b3d4-11ea-8b22-0d44aa5cd316.png)

With Lighted Poles, Reskins-Bobs and Bob's Power and Logistics enabled, the skin changes made by the reskins don't apply to lighted poles. This is likely due to the fact that reskins runs in final fixes due to compatibility issues if done otherwise.

Is there any way to solve this? Save below.
[LightedPoles-BugReport.zip](https://github.com/Yousei9/Lighted-Poles-Plus/files/4810296/LightedPoles-BugReport.zip)

**Comment by Yousei9** [comment]
Solvable if those other mods mentioned use dependencies instead of relying on final-fixes.
LEP+ will not be moved to final fixes, because other mods may depend on my poles being completed in data-update.
